name = "acsd-pec"
version = "0.3.0"
defaultTargets = ["ACSD", "acsd-transcript-checker", "acsd-rats-transcript-checker"]

[[lean_lib]]
name = "ACSD"

[[lean_exe]]
name = "acsd-transcript-checker"
root = "TranscriptCli"

[[lean_exe]]
name = "acsd-rats-transcript-checker"
root = "RatsTranscriptCli"
